version: 2

project_name: "obot"

builds:
  - id: build
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X "github.com/obot-platform/obot/pkg/version.Tag=v{{ .Version }}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: "obot-platform"
    name: "obot"
  make_latest: false
  prerelease: auto

brews:
  - name: obot
    description: "Obot CLI"
    install: |
      bin.install "obot"
    homepage: "https://github.com/obot-platform/obot"
    skip_upload: false
    directory: "Formula"
    repository:
      owner: obot-platform
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
