version: 2

project_name: "acorn"

builds:
  - id: build
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X "github.com/acorn-io/acorn/pkg/version.Tag=v{{ .Version }}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: "acorn-io"
    name: "acorn"
  make_latest: false
  prerelease: auto

brews:
  - name: acorn
    description: "Acorn CLI"
    install: |
      bin.install "acorn"
    homepage: "https://github.com/acorn-io/acorn"
    skip_upload: false
    directory: "Formula"
    repository:
      owner: acorn-io
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
