name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: depot-ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Depot
      uses: depot/setup-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: depot/build-push-action@v1
      with:
        project: bbqjs4tj1g
        context: .
        token: ${{ secrets.DEPOT_TOKEN }}
        push: true
        tags: ghcr.io/${{ github.repository }}:main

    - name: Deploy to Test Render
      uses: joelwmale/webhook-action@2.4.1
      with:
        url: ${{ secrets.RENDER_TEST_DEPLOY_URL }}

    - name: Deploy to Main Render
      uses: joelwmale/webhook-action@2.4.1
      with:
        url: ${{ secrets.RENDER_MAIN_DEPLOY_URL }}
